icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
# idle_bg = "#285577"
# idle_fg = "#abcdef"

[icons]
icons = "material-nf"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "net"
format = " $icon { $signal_strength $ssid|Wired connection} "

[[block]]
block = "backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
max_vol = 100
# [[block.click]]
# button = "left"
# cmd = "pavucontrol"

[[block]]
block = "sound"
format = " $icon "
driver = "pulseaudio"
device_kind = "source"

[[block]]
block = "bluetooth"
mac = "35:55:0C:93:00:CA"
disconnected_format = ""
format = " $icon {$percentage }"
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon $percentage "
full_threshold = 70

[[block]]
block = "time"
interval = 5
timezone = "Asia/Bangkok"
format = " $timestamp.datetime(f:'%a %d/%m %R') "
